import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import AIPulseLine from '../components/AIPulseLine'
import SEO from '../components/SEO'

export default function PrivacyPolicy() {
  useEffect(() => { window.scrollTo(0, 0) }, [])

  return (
    <div className="pt-36 pb-24 px-6">
      <SEO title="Privacy Policy" description="Your data is exactly that—yours. We don't want it, we don't track it, and we can't see it." url="/privacy-policy" />
      <article className="max-w-[700px] mx-auto">
        
        {/* Header */}
        <header className="mb-24">
          <div className="mb-4">
            <span className="font-label font-semibold uppercase tracking-[0.2em] text-[10px] text-[#474747]">
              LEGAL
            </span>
          </div>
          <h1 className="font-headline font-black text-6xl md:text-8xl tracking-[-0.03em] leading-[0.9] text-black mb-8">
            Privacy Policy
          </h1>
          <div className="h-1 w-24 bg-black mb-12" />
          <p className="text-xl md:text-2xl font-medium text-[#474747] leading-relaxed italic">
            Your data is exactly that—yours. We don't want it, we don't track it, and we can't see it.
          </p>
        </header>

        <AIPulseLine className="mb-24" />

        {/* Content */}
        <section className="space-y-16">
          
          <div>
            <div className="flex items-center gap-4 mb-6">
              <span className="material-symbols-outlined text-black">security</span>
              <h2 className="font-headline font-bold text-2xl uppercase tracking-tight">1. No Cloud. No Tracking.</h2>
            </div>
            <div className="space-y-6 text-[#474747] leading-8 text-lg">
              <p>
                At VOX LOCAL, our fundamental principle is privacy through local processing. We do not transmit your voice data, transcripts, or personal information to any cloud servers. Everything runs entirely on your device.
              </p>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-4 mb-6">
              <span className="material-symbols-outlined text-black">folder</span>
              <h2 className="font-headline font-bold text-2xl uppercase tracking-tight">2. Data Storage</h2>
            </div>
            <div className="space-y-6 text-[#474747] leading-8 text-lg">
              <p>
                All data generated by VOX LOCAL, including audio recordings and text transcripts, is stored exclusively on your local hard drive. We do not have access to this data, and we cannot recover it if it is lost or deleted from your device.
              </p>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-4 mb-6">
              <span className="material-symbols-outlined text-black">hub</span>
              <h2 className="font-headline font-bold text-2xl uppercase tracking-tight">3. Third-Party Integrations</h2>
            </div>
            <div className="space-y-6 text-[#474747] leading-8 text-lg">
              <p>
                VOX LOCAL offers integrations with third-party tools (like Notion, Obsidian, and Excel). When you choose to export your data to these services, the data transfer happens directly between your device and the third-party API. VOX LOCAL does not act as a middleman in these transfers. Please review the privacy policies of the respective third-party services you choose to connect.
              </p>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-4 mb-6">
              <span className="material-symbols-outlined text-black">visibility_off</span>
              <h2 className="font-headline font-bold text-2xl uppercase tracking-tight">4. Telemetry and Analytics</h2>
            </div>
            <div className="space-y-6 text-[#474747] leading-8 text-lg">
              <p>
                We do not collect any usage analytics, crash reports, or telemetry data. Our software is designed to operate completely offline if necessary, ensuring your interactions remain completely private.
              </p>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-4 mb-6">
              <span className="material-symbols-outlined text-black">update</span>
              <h2 className="font-headline font-bold text-2xl uppercase tracking-tight">5. Changes to This Policy</h2>
            </div>
            <div className="space-y-6 text-[#474747] leading-8 text-lg">
              <p>
                We may update our Privacy Policy from time to time. Any changes will be reflected in the software updates and on this page. By continuing to use VOX LOCAL, you agree to the updated terms.
              </p>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-4 mb-6">
              <span className="material-symbols-outlined text-black">mail</span>
              <h2 className="font-headline font-bold text-2xl uppercase tracking-tight">6. Contact Us</h2>
            </div>
            <div className="space-y-6 text-[#474747] leading-8 text-lg">
              <p>
                If you have any questions about our privacy practices, please contact us through our official support channels provided on our website or GitHub repository.
              </p>
            </div>
          </div>

        </section>

        <AIPulseLine className="mt-32 mb-16" />

        {/* Article footer CTA */}
        <footer className="pt-12 text-center">
          <p className="font-headline font-bold text-xl mb-2">Back to Local Sovereignty.</p>
          <p className="text-[#474747] text-sm mb-8">Run your AI. Keep your data. Own your intelligence.</p>
          <Link to="/">
            <button className="cta-gradient text-[#e2e2e2] px-12 py-4 text-xs font-bold uppercase tracking-[0.2em] cursor-pointer">
              Return Home
            </button>
          </Link>
        </footer>

      </article>
    </div>
  )
}
